spring.application.name=credit-appsec-demo.git
<<<<<<< HEAD
=======
spring.datasource.url=jdbc:h2:mem:creditdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# VULNERABILITY #4: hardcoded example AWS key
aws.access.key=AKIAIOSFODNN7EXAMPLE
aws.secret.key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
>>>>>>> feature/Day2
